version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Install phase"
      - npm install # Install dependencies
      # Add any other installation commands here

  pre_build:
    commands:
      - echo "Pre-build phase"
      - npm test --watchAll=false
      # Add any pre-build commands here

  build:
    commands:
      - echo "Build phase"
      - npm run build
      # Add your build commands here

  post_build:
    commands:
      - echo "Post-build phase"
      # Add any post-build commands here

artifacts:
  files:
    - '**/*'
